### ISSUE TITLE
Publish Docker image with included kafkaui-glue-sr-serde

### ISSUE THREAD

**Issue by RamazanYapparov** [provectus/kafkaui-glue-sr-serde#13]
Running kafka ui with this serde is not possible without cloning this repository and building it from source. The jar file from [this release](https://github.com/provectus/kafkaui-glue-sr-serde/releases/tag/1.0.0) is not compatible too (I guess it's lack of dependencies).

Would be really great to have an image that works out of the box.

**Comment by Haarolean** [comment]
#10 might be the problem

**Comment by RamazanYapparov** [comment]
Any estimates on that?

**Comment by RamazanYapparov** [comment]
@Haarolean looks like #10 was fixed by #11 some time ago, so new releases should be good?

**Comment by Haarolean** [comment]
@RamazanYapparov can you check if this jar does work for you?
https://github.com/provectus/kafkaui-glue-sr-serde/releases/tag/v1.0.1-SNAPSHOT

**Comment by RamazanYapparov** [comment]
Yes, thank you!

**Comment by Haarolean** [comment]
Ok, nice.
[1.0.1](https://github.com/provectus/kafkaui-glue-sr-serde/releases/tag/1.0.1) is out in this case.
