### ISSUE TITLE
Glue Schema Registry not found within Kafka UI using IAM Auth

### ISSUE THREAD

**Issue by fcanas-endava** [provectus/kafkaui-glue-sr-serde#22]
Hi,

I've deployed an instance of Kafka-ui within an EKS cluster using Helm. The UI is working properly for Topics/Brokers/etc. but for some reason the Glue Schema Registry is not present within the UI even with the Glue Schema Serde config. I'm using the SASL AWS_MSK_IAM to authenticate the MSK cluster. Here's a piece of my code:

yamlApplicationConfig: 
  kafka:
    clusters:
      - name: my-cluster
        bootstrapServers: amazonaws.com:9098
        properties:
          security.protocol: SASL_SSL
          sasl.mechanism: AWS_MSK_IAM
          sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler
          sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;
        serde: 
          - name: GlueSchemaRegistry
            className: com.provectus.kafka.ui.serdes.glue.GlueSerde
            filePath: /some-path/kafkaui-glue-serde-1.0-SNAPSHOT-jar-with-dependencies.jar
            properties:
              region: us-east-1
              registry: registry-name
              keySchemaNameTemplate: "%s-key"
              valueSchemaNameTemplate: "%s-value"

Looking forward to your comments.

Best,

**Comment by Haarolean** [comment]
Hi @fcanas-endava,
have you built and image with glue artifcact included?

**Comment by fcanas-endava** [comment]
hey @Haarolean I extended the Provectus Kafka-UI image and added the glue artifact including all dependencies. Also I'm checking the logs on the EKS pod where Kafka-UI is being deployed and it shows that it's taking the serde config and it's not showing any errors, however, I'm not sure if I'm missing something. I'll attach the pod logs for reference.

<img width="981" alt="Screenshot 2023-08-11 at 09 41 07" src="https://github.com/provectus/kafkaui-glue-sr-serde/assets/129789767/0fd5c441-8417-4498-ae7d-2befc3a08676">

**Comment by fcanas-endava** [comment]
@Haarolean  I was reviewing Kafka UI and it seems the Glue Schema Serde it's working in some ways, for example I can choose the Key Serde and Value Serde for messages  using the Glue Schema Registry as seen under this screenshot. The only thing missing is the option for "Schemas" on the left hand side of the UI.
![Screenshot 2023-08-11 at 11 04 03](https://github.com/provectus/kafkaui-glue-sr-serde/assets/129789767/b1b9f20a-308b-4f77-abf4-d677b8781a8b)

**Comment by Haarolean** [comment]
@fcanas-endava I see what you mean now. We do not support editing glue schemas like with SR, just (de-)serializing messages. 
Feel free to raise an issue in kafka-ui repo so we could consider this. Thanks!

**Comment by fcanas-endava** [comment]
@Haarolean Thank you for your clarification on this.
